namespace Shared.Quest;

public enum QuestEventType
{
	Invalid = -1,
	Collected,
	Hunted,
	Crafted,
	Built,
	Grown,
	Farmed,
	Died,
	Explored,
	EstateManaged,
	Emigrated,
	MissionUpdated,
	AdvisorUpdated,
	CustomEvent,
	TitleUpdated,
	FactionUpdated,
	S02Survived,
	AnimalTamed,
	PetDomesticated,
	PetBelonged,
	ArchipelagoCompleted,
	EliteSpawnDetected,
	EstimateTechSupport,
	TechSupportItem,
	EncyclopediaCompleted,
	ClanDonate,
	HasFriends,
	MarketRegister,
	AbilityResult,
	Deposited,
	VoucherUsed,
	PeriodicPurchaseRemained,
	PlayMiniGame,
	WarpAcceleratorRewarded,
	StatusEffectsActivated,
	FactionSupportRequested,
	HasItems,
	Memo,
	ItemUsed
}
