using System.Collections.Generic;
using Messages;

namespace DurangoServer.Core;

/// <summary>
/// ข้อมูลพืชผล + ปุ๋ย + ภาชนะตักน้ำ — **สร้างอัตโนมัติ อย่าแก้ด้วยมือ**
/// (`python scripts/extract_crops.py "../game/DurangoV2_Data/resources.strings.txt" ServerCore/CropData.cs ServerCore/ItemTagData.cs`)
///
/// · <see cref="CropInfo.GrowBase"/> เป็น **วินาที** ตามเกมจริง (ยาวถึง 24 ชม.)
///   เซิร์ฟย่อด้วย <c>Farming.GrowthScale</c> ใน config.json อีกที
/// · <see cref="CropInfo.ProductTags"/> เดาจาก tag ของเมล็ด (ข้อมูลเกมไม่มี tag ของผลผลิต)
/// </summary>
public static class CropData
{
    public struct CropInfo
    {
        /// <summary>prototype ของเมล็ด เช่น corn_seed</summary>
        public string SeedId;
        public string Name;
        public string Icon;
        public int MaxLevel;

        /// <summary>ผลผลิตหลักตอนเก็บเกี่ยว เช่น corn_crop</summary>
        public string ProductId;
        public string ProductName;
        public string ProductIcon;
        /// <summary>tag ของผลผลิต — เดาจาก tag ของเมล็ด (ตัด plantable ออก)</summary>
        public Tag[] ProductTags;

        /// <summary>เมล็ดที่ได้คืนตอนเก็บเกี่ยว เช่น corn_seed_crop (null = พืชชนิดนี้ไม่คืนเมล็ด)</summary>
        public string SeedProductId;
        public string SeedProductName;
        public string SeedProductIcon;

        /// <summary>เวลาโตเป็นวินาทีที่เมล็ดเลเวล 1</summary>
        public float GrowBase;
        public float GrowPerLevel;

        public int RequiredWater;
        public int RequiredFertilizer;
        /// <summary>ผลผลิตที่ได้เพิ่มเมื่อใส่ปุ๋ยเต็ม (นอกเหนือจาก 1 ชิ้นพื้นฐาน)</summary>
        public int AdditionalProduct;
        /// <summary>ความทนของพืช — ใช้เป็นเกณฑ์ว่ารดน้ำไม่ครบแค่ไหนถึงจะตาย</summary>
        public float Survivability;

        /// <summary>ไบโอมที่พืชชนิดนี้ชอบ (Invalid = ปลูกที่ไหนก็ได้)</summary>
        public Shared.Region.Biome Preference;

        public string[] GrownLooks;
        public string GrowingLook;
        public string DeadLook;

        /// <summary>เวลาโตของเมล็ดเลเวลนี้ (ยังไม่คูณ GrowthScale)</summary>
        public float GrowSecondsAt(int level)
        {
            float v = GrowBase + GrowPerLevel * (level - 1);
            return v < 1f ? 1f : v;
        }

        /// <summary>หน้าตาของต้นที่โตแล้ว — เลือกจากพิกัดให้แปลงเดิมได้ต้นเดิมเสมอ</summary>
        public string GrownLookFor(int tileX, int tileY)
        {
            if (GrownLooks == null || GrownLooks.Length == 0)
            {
                return null;
            }
            int h = (tileX * 73856093) ^ (tileY * 19349663);
            if (h < 0)
            {
                h = -h;
            }
            return GrownLooks[h % GrownLooks.Length];
        }
    }

    public static readonly Dictionary<string, CropInfo> ById = new Dictionary<string, CropInfo>
    {
        { "apple_seed", new CropInfo
          {
              SeedId = "apple_seed",
              Name = "사과",
              Icon = "icon_nat_fruit_apple",
              MaxLevel = 60,
              ProductId = "apple_crop",
              ProductName = "사과",
              ProductIcon = "icon_nat_fruit_apple",
              ProductTags = new[] { new Tag { Id = "eatable", Level = 1 }, new Tag { Id = "fruit", Level = 1 } },
              SeedProductId = null,
              SeedProductName = null,
              SeedProductIcon = null,
              GrowBase = 600.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 0,
              RequiredFertilizer = 0,
              AdditionalProduct = 0,
              Survivability = 1.00f,
              Preference = Shared.Region.Biome.Invalid,
              GrownLooks = new[] { "appletree" },
              GrowingLook = "ML11_02",
              DeadLook = "AG03_01"
          } },
        { "banana_seed", new CropInfo
          {
              SeedId = "banana_seed",
              Name = "바나나나무",
              Icon = "icon_nat_fruit_banana",
              MaxLevel = 60,
              ProductId = "banana_crop",
              ProductName = "바나나",
              ProductIcon = "icon_nat_fruit_banana",
              ProductTags = new[] { new Tag { Id = "eatable", Level = 1 }, new Tag { Id = "fruit", Level = 1 } },
              SeedProductId = "banana_seed_crop",
              SeedProductName = "바나나 종자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 75600.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 12,
              RequiredFertilizer = 200,
              AdditionalProduct = 30,
              Survivability = 0.82f,
              Preference = Shared.Region.Biome.TropicalForest,
              GrownLooks = new[] { "TR13" },
              GrowingLook = "ML11_02",
              DeadLook = "AG03_01"
          } },
        { "barley_seed", new CropInfo
          {
              SeedId = "barley_seed",
              Name = "보리",
              Icon = "icon_nat_farm_barley",
              MaxLevel = 60,
              ProductId = "barley_crop",
              ProductName = "보리쌀",
              ProductIcon = "icon_nat_farm_barley",
              ProductTags = new[] { new Tag { Id = "eatable", Level = 1 }, new Tag { Id = "grain", Level = 1 } },
              SeedProductId = "barley_seed_crop",
              SeedProductName = "보리쌀 종자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 10800.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 3,
              RequiredFertilizer = 50,
              AdditionalProduct = 7,
              Survivability = 0.80f,
              Preference = Shared.Region.Biome.TemperateForest,
              GrownLooks = new[] { "Barley_02_b" },
              GrowingLook = "sprout_01",
              DeadLook = "AG03_01"
          } },
        { "bean_seed", new CropInfo
          {
              SeedId = "bean_seed",
              Name = "콩",
              Icon = "icon_nat_farm_bean",
              MaxLevel = 60,
              ProductId = "bean_crop",
              ProductName = "콩",
              ProductIcon = "icon_nat_farm_bean",
              ProductTags = new[] { new Tag { Id = "eatable", Level = 1 }, new Tag { Id = "grain", Level = 1 } },
              SeedProductId = "bean_seed_crop",
              SeedProductName = "콩 종자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 5400.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 4,
              RequiredFertilizer = 50,
              AdditionalProduct = 7,
              Survivability = 0.83f,
              Preference = Shared.Region.Biome.Grassland,
              GrownLooks = new[] { "HG17" },
              GrowingLook = "sprout_01",
              DeadLook = "AG03_01"
          } },
        { "carnation_seed", new CropInfo
          {
              SeedId = "carnation_seed",
              Name = "카네이션",
              Icon = "icon_nat_farm_carnation",
              MaxLevel = 60,
              ProductId = "carnation_crop",
              ProductName = null,
              ProductIcon = null,
              ProductTags = new[] { new Tag { Id = "eatable", Level = 1 } },
              SeedProductId = null,
              SeedProductName = null,
              SeedProductIcon = null,
              GrowBase = 9000.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 5,
              RequiredFertilizer = 80,
              AdditionalProduct = 10,
              Survivability = 0.80f,
              Preference = Shared.Region.Biome.TemperateForest,
              GrownLooks = new[] { "FL57" },
              GrowingLook = "sprout_01",
              DeadLook = "AG03_01"
          } },
        { "cherryblossom_01_seed", new CropInfo
          {
              SeedId = "cherryblossom_01_seed",
              Name = "벚나무",
              Icon = "icon_nat_cherryblossom_01",
              MaxLevel = 60,
              ProductId = "cherryblossom_01_crop",
              ProductName = null,
              ProductIcon = null,
              ProductTags = new[] { new Tag { Id = "eatable", Level = 1 }, new Tag { Id = "fruit", Level = 1 } },
              SeedProductId = "cherryblossom_01_seed_crop",
              SeedProductName = "버찌",
              SeedProductIcon = "icon_nat_fruit_cranberry",
              GrowBase = 14400.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 10,
              RequiredFertilizer = 20,
              AdditionalProduct = 6,
              Survivability = 0.90f,
              Preference = Shared.Region.Biome.TemperateForest,
              GrownLooks = new[] { "cb_small_01", "cb_small_02" },
              GrowingLook = "ML11_02",
              DeadLook = "AG03_01"
          } },
        { "cherryblossom_02_seed", new CropInfo
          {
              SeedId = "cherryblossom_02_seed",
              Name = "겹벚나무",
              Icon = "icon_nat_cherryblossom_02",
              MaxLevel = 60,
              ProductId = "cherryblossom_02_crop",
              ProductName = null,
              ProductIcon = null,
              ProductTags = new[] { new Tag { Id = "seeding", Level = 1 } },
              SeedProductId = "cherryblossom_02_seed_crop",
              SeedProductName = "겹벚나무 묘목",
              SeedProductIcon = "icon_nat_seeding",
              GrowBase = 14400.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 15,
              RequiredFertilizer = 20,
              AdditionalProduct = 7,
              Survivability = 0.90f,
              Preference = Shared.Region.Biome.TemperateForest,
              GrownLooks = new[] { "cb_middle_01", "cb_middle_02" },
              GrowingLook = "ML11_02",
              DeadLook = "AG03_01"
          } },
        { "chilipepper_seed", new CropInfo
          {
              SeedId = "chilipepper_seed",
              Name = "고추",
              Icon = "icon_nat_farm_chilipepper",
              MaxLevel = 60,
              ProductId = "chilipepper_crop",
              ProductName = "고추",
              ProductIcon = "icon_nat_farm_chilipepper",
              ProductTags = new[] { new Tag { Id = "eatable", Level = 1 }, new Tag { Id = "vegetable", Level = 1 } },
              SeedProductId = "chilipepper_seed_crop",
              SeedProductName = "고추 종자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 32400.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 10,
              RequiredFertilizer = 170,
              AdditionalProduct = 17,
              Survivability = 0.82f,
              Preference = Shared.Region.Biome.TropicalForest,
              GrownLooks = new[] { "AG03_09" },
              GrowingLook = "sprout_01",
              DeadLook = "AG03_01"
          } },
        { "coffee_seed", new CropInfo
          {
              SeedId = "coffee_seed",
              Name = "커피 나무",
              Icon = "icon_nat_fruit_coffee",
              MaxLevel = 60,
              ProductId = "coffee_crop",
              ProductName = null,
              ProductIcon = null,
              ProductTags = new[] { new Tag { Id = "eatable", Level = 1 } },
              SeedProductId = "coffee_seed_crop",
              SeedProductName = "커피 종자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 86400.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 12,
              RequiredFertilizer = 200,
              AdditionalProduct = 16,
              Survivability = 0.80f,
              Preference = Shared.Region.Biome.TropicalForest,
              GrownLooks = new[] { "TR08" },
              GrowingLook = "ML11_02",
              DeadLook = "AG03_01"
          } },
        { "corn_seed", new CropInfo
          {
              SeedId = "corn_seed",
              Name = "옥수수",
              Icon = "icon_nat_farm_corn",
              MaxLevel = 60,
              ProductId = "corn_crop",
              ProductName = "옥수수",
              ProductIcon = "icon_nat_farm_corn",
              ProductTags = new[] { new Tag { Id = "eatable", Level = 1 }, new Tag { Id = "grain", Level = 1 }, new Tag { Id = "vegetable", Level = 1 } },
              SeedProductId = "corn_seed_crop",
              SeedProductName = "옥수수 종자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 330.0f,
              GrowPerLevel = 30.0f,
              RequiredWater = 2,
              RequiredFertilizer = 20,
              AdditionalProduct = 5,
              Survivability = 0.90f,
              Preference = Shared.Region.Biome.Grassland,
              GrownLooks = new[] { "AG20" },
              GrowingLook = "sprout_01",
              DeadLook = "AG03_01"
          } },
        { "cosmos_seed", new CropInfo
          {
              SeedId = "cosmos_seed",
              Name = "코스모스",
              Icon = "icon_nat_cosmos",
              MaxLevel = 60,
              ProductId = "cosmos_crop",
              ProductName = null,
              ProductIcon = null,
              ProductTags = new[] { new Tag { Id = "eatable", Level = 1 }, new Tag { Id = "grain", Level = 1 } },
              SeedProductId = "cosmos_seed_crop",
              SeedProductName = "코스모스 종자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 21600.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 2,
              RequiredFertilizer = 70,
              AdditionalProduct = 11,
              Survivability = 0.80f,
              Preference = Shared.Region.Biome.TemperateForest,
              GrownLooks = new[] { "co_02_a" },
              GrowingLook = "sprout_01",
              DeadLook = "AG03_01"
          } },
        { "cotton_seed", new CropInfo
          {
              SeedId = "cotton_seed",
              Name = "목화",
              Icon = "icon_nat_cotton",
              MaxLevel = 60,
              ProductId = "cotton_crop",
              ProductName = "솜",
              ProductIcon = "icon_nat_cotton",
              ProductTags = new[] { new Tag { Id = "fiber", Level = 1 } },
              SeedProductId = "cotton_seed_crop",
              SeedProductName = "목화 종자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 21600.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 3,
              RequiredFertilizer = 100,
              AdditionalProduct = 11,
              Survivability = 0.83f,
              Preference = Shared.Region.Biome.Tundra,
              GrownLooks = new[] { "AG08" },
              GrowingLook = "sprout_01",
              DeadLook = "AG03_01"
          } },
        { "desertagave_seed", new CropInfo
          {
              SeedId = "desertagave_seed",
              Name = "사막용설란",
              Icon = "icon_nat_desertagave",
              MaxLevel = 60,
              ProductId = "desertagave_crop",
              ProductName = "과육",
              ProductIcon = "icon_nat_desertagave",
              ProductTags = null,
              SeedProductId = "desertagave_seed_crop",
              SeedProductName = "사막용설란 종자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 43200.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 20,
              RequiredFertilizer = 200,
              AdditionalProduct = 16,
              Survivability = 0.80f,
              Preference = Shared.Region.Biome.Desert,
              GrownLooks = new[] { "SW02_farm" },
              GrowingLook = "sprout_01",
              DeadLook = "AG03_01"
          } },
        { "dogrose_seed", new CropInfo
          {
              SeedId = "dogrose_seed",
              Name = "들장미",
              Icon = "icon_nat_flower2",
              MaxLevel = 60,
              ProductId = "dogrose_crop",
              ProductName = null,
              ProductIcon = null,
              ProductTags = null,
              SeedProductId = "dogrose_seed_crop",
              SeedProductName = "들장미 종자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 10800.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 6,
              RequiredFertilizer = 70,
              AdditionalProduct = 6,
              Survivability = 0.83f,
              Preference = Shared.Region.Biome.TemperateForest,
              GrownLooks = new[] { "SH19" },
              GrowingLook = "sprout_01",
              DeadLook = "AG03_01"
          } },
        { "fig_seed", new CropInfo
          {
              SeedId = "fig_seed",
              Name = "무화과 나무",
              Icon = "icon_nat_fruit_fig",
              MaxLevel = 60,
              ProductId = "fig_crop",
              ProductName = null,
              ProductIcon = null,
              ProductTags = null,
              SeedProductId = "fig_seed_crop",
              SeedProductName = "무화과 종자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 36000.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 10,
              RequiredFertilizer = 150,
              AdditionalProduct = 18,
              Survivability = 0.85f,
              Preference = Shared.Region.Biome.TemperateForest,
              GrownLooks = new[] { "SH07_beach" },
              GrowingLook = "ML11_02",
              DeadLook = "AG03_01"
          } },
        { "flax_seed", new CropInfo
          {
              SeedId = "flax_seed",
              Name = "아마",
              Icon = "icon_nat_fiber_flax",
              MaxLevel = 60,
              ProductId = "flax_crop",
              ProductName = "아마 줄기",
              ProductIcon = "icon_nat_fiber_flax",
              ProductTags = new[] { new Tag { Id = "fiber", Level = 1 } },
              SeedProductId = "flax_seed_crop",
              SeedProductName = "아마 종자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 5400.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 2,
              RequiredFertilizer = 50,
              AdditionalProduct = 6,
              Survivability = 0.83f,
              Preference = Shared.Region.Biome.Grassland,
              GrownLooks = new[] { "GC01" },
              GrowingLook = "sprout_01",
              DeadLook = "AG03_01"
          } },
        { "flax_tropical_seed", new CropInfo
          {
              SeedId = "flax_tropical_seed",
              Name = "열대 아마",
              Icon = "icon_nat_fiber_flax",
              MaxLevel = 60,
              ProductId = "flax_tropical_crop",
              ProductName = "열대 아마 줄기",
              ProductIcon = "icon_nat_fiber_flax",
              ProductTags = new[] { new Tag { Id = "fiber", Level = 1 } },
              SeedProductId = "flax_tropical_seed_crop",
              SeedProductName = "열대 아마 종자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 21600.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 8,
              RequiredFertilizer = 60,
              AdditionalProduct = 11,
              Survivability = 0.83f,
              Preference = Shared.Region.Biome.TropicalForest,
              GrownLooks = new[] { "GC02" },
              GrowingLook = "sprout_01",
              DeadLook = "AG03_01"
          } },
        { "ginkgotree_seed", new CropInfo
          {
              SeedId = "ginkgotree_seed",
              Name = "은행 나무",
              Icon = "icon_nat_ginkgotree",
              MaxLevel = 60,
              ProductId = "ginkgotree_crop",
              ProductName = null,
              ProductIcon = null,
              ProductTags = null,
              SeedProductId = "ginkgotree_seed_crop",
              SeedProductName = "은행 나무 종자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 86400.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 30,
              RequiredFertilizer = 200,
              AdditionalProduct = 20,
              Survivability = 0.80f,
              Preference = Shared.Region.Biome.Grassland,
              GrownLooks = new[] { "AF19_02" },
              GrowingLook = "ML11_02",
              DeadLook = "AG03_01"
          } },
        { "grape_seed", new CropInfo
          {
              SeedId = "grape_seed",
              Name = "포도나무",
              Icon = "icon_nat_farm_grape",
              MaxLevel = 60,
              ProductId = "grape_crop",
              ProductName = "포도",
              ProductIcon = "icon_nat_farm_grape",
              ProductTags = new[] { new Tag { Id = "eatable", Level = 1 }, new Tag { Id = "fruit", Level = 1 } },
              SeedProductId = "grape_seed_crop",
              SeedProductName = "포도 종자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 32400.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 10,
              RequiredFertilizer = 130,
              AdditionalProduct = 16,
              Survivability = 0.83f,
              Preference = Shared.Region.Biome.TemperateForest,
              GrownLooks = new[] { "AG19_06" },
              GrowingLook = "ML11_02",
              DeadLook = "AG03_01"
          } },
        { "halloween_pumpkin_seed", new CropInfo
          {
              SeedId = "halloween_pumpkin_seed",
              Name = "수상한 호박",
              Icon = "icon_nat_farm_pumpkin",
              MaxLevel = 60,
              ProductId = "halloween_pumpkin_crop",
              ProductName = "수상한 호박",
              ProductIcon = "icon_nat_halloween_pumpkin",
              ProductTags = new[] { new Tag { Id = "eatable", Level = 1 }, new Tag { Id = "vegetable", Level = 1 } },
              SeedProductId = "halloween_pumpkin_seed_crop",
              SeedProductName = "수상한 호박 종자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 3600.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 5,
              RequiredFertilizer = 50,
              AdditionalProduct = 10,
              Survivability = 0.85f,
              Preference = Shared.Region.Biome.Tundra,
              GrownLooks = new[] { "pumpkin_01", "pumpkin_02" },
              GrowingLook = "sprout_01",
              DeadLook = "AG03_01"
          } },
        { "halloween_spidertree_seed", new CropInfo
          {
              SeedId = "halloween_spidertree_seed",
              Name = "거미줄 나무",
              Icon = "icon_nat_spider_web",
              MaxLevel = 60,
              ProductId = "halloween_spidertree_crop",
              ProductName = null,
              ProductIcon = null,
              ProductTags = new[] { new Tag { Id = "eatable", Level = 1 } },
              SeedProductId = "halloween_spidertree_seed_crop",
              SeedProductName = "거미줄 나무 종자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 75600.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 10,
              RequiredFertilizer = 150,
              AdditionalProduct = 10,
              Survivability = 0.80f,
              Preference = Shared.Region.Biome.Tundra,
              GrownLooks = new[] { "halloween_tree_02", "halloween_tree_03" },
              GrowingLook = "ML11_02",
              DeadLook = "AG03_01"
          } },
        { "jasmine_seed", new CropInfo
          {
              SeedId = "jasmine_seed",
              Name = "재스민",
              Icon = "icon_nat_jasmine",
              MaxLevel = 60,
              ProductId = "jasmine_crop",
              ProductName = null,
              ProductIcon = null,
              ProductTags = new[] { new Tag { Id = "eatable", Level = 1 } },
              SeedProductId = "jasmine_seed_crop",
              SeedProductName = "재스민 종자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 5400.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 3,
              RequiredFertilizer = 30,
              AdditionalProduct = 10,
              Survivability = 0.80f,
              Preference = Shared.Region.Biome.TropicalForest,
              GrownLooks = new[] { "Jasmine_01" },
              GrowingLook = "sprout_01",
              DeadLook = "AG03_01"
          } },
        { "jpapricot_01_seed", new CropInfo
          {
              SeedId = "jpapricot_01_seed",
              Name = "매화나무",
              Icon = "icon_nat_jpapricot",
              MaxLevel = 60,
              ProductId = "jpapricot_01_crop",
              ProductName = null,
              ProductIcon = null,
              ProductTags = null,
              SeedProductId = "jpapricot_01_seed_crop",
              SeedProductName = "매화나무 종자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 75600.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 30,
              RequiredFertilizer = 100,
              AdditionalProduct = 12,
              Survivability = 0.80f,
              Preference = Shared.Region.Biome.Grassland,
              GrownLooks = new[] { "BS10_01" },
              GrowingLook = "ML11_02",
              DeadLook = "AG03_01"
          } },
        { "jpapricot_02_seed", new CropInfo
          {
              SeedId = "jpapricot_02_seed",
              Name = "붉은 매화나무",
              Icon = "icon_nat_jpapricot",
              MaxLevel = 60,
              ProductId = "jpapricot_02_crop",
              ProductName = null,
              ProductIcon = null,
              ProductTags = null,
              SeedProductId = "jpapricot_02_seed_crop",
              SeedProductName = "붉은 매화나무 종자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 75600.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 30,
              RequiredFertilizer = 100,
              AdditionalProduct = 10,
              Survivability = 0.80f,
              Preference = Shared.Region.Biome.Grassland,
              GrownLooks = new[] { "BS10_02" },
              GrowingLook = "ML11_02",
              DeadLook = "AG03_01"
          } },
        { "jpapricot_03_seed", new CropInfo
          {
              SeedId = "jpapricot_03_seed",
              Name = "하얀 매화나무",
              Icon = "icon_nat_jpapricot",
              MaxLevel = 60,
              ProductId = "jpapricot_03_crop",
              ProductName = null,
              ProductIcon = null,
              ProductTags = null,
              SeedProductId = "jpapricot_03_seed_crop",
              SeedProductName = "하얀 매화나무 종자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 75600.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 30,
              RequiredFertilizer = 100,
              AdditionalProduct = 10,
              Survivability = 0.80f,
              Preference = Shared.Region.Biome.Grassland,
              GrownLooks = new[] { "BS10_03" },
              GrowingLook = "ML11_02",
              DeadLook = "AG03_01"
          } },
        { "lavender_seed", new CropInfo
          {
              SeedId = "lavender_seed",
              Name = "라벤더",
              Icon = "icon_nat_farm_lavender",
              MaxLevel = 60,
              ProductId = "lavender_crop",
              ProductName = null,
              ProductIcon = null,
              ProductTags = null,
              SeedProductId = "lavender_seed_crop",
              SeedProductName = "라벤더 종자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 21600.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 8,
              RequiredFertilizer = 100,
              AdditionalProduct = 11,
              Survivability = 0.83f,
              Preference = Shared.Region.Biome.Grassland,
              GrownLooks = new[] { "AG11" },
              GrowingLook = "sprout_01",
              DeadLook = "AG03_01"
          } },
        { "mango_seed", new CropInfo
          {
              SeedId = "mango_seed",
              Name = "망고",
              Icon = "icon_nat_fruit_mango",
              MaxLevel = 60,
              ProductId = "mango_crop",
              ProductName = "망고",
              ProductIcon = "icon_nat_fruit_mango",
              ProductTags = new[] { new Tag { Id = "eatable", Level = 1 } },
              SeedProductId = "mango_seed_crop",
              SeedProductName = "망고 종자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 32400.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 10,
              RequiredFertilizer = 130,
              AdditionalProduct = 15,
              Survivability = 0.70f,
              Preference = Shared.Region.Biome.TropicalForest,
              GrownLooks = new[] { "TR12" },
              GrowingLook = "ML11_02",
              DeadLook = "AG03_01"
          } },
        { "mapletree_seed", new CropInfo
          {
              SeedId = "mapletree_seed",
              Name = "단풍 나무",
              Icon = "icon_nat_mapletree",
              MaxLevel = 60,
              ProductId = "mapletree_crop",
              ProductName = null,
              ProductIcon = null,
              ProductTags = null,
              SeedProductId = "mapletree_seed_crop",
              SeedProductName = "단풍 나무 종자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 86400.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 30,
              RequiredFertilizer = 100,
              AdditionalProduct = 10,
              Survivability = 0.80f,
              Preference = Shared.Region.Biome.Grassland,
              GrownLooks = new[] { "AL17" },
              GrowingLook = "ML11_02",
              DeadLook = "AG03_01"
          } },
        { "mushroom_seed", new CropInfo
          {
              SeedId = "mushroom_seed",
              Name = "버섯",
              Icon = "icon_nat_mushroom",
              MaxLevel = 60,
              ProductId = "mushroom_crop",
              ProductName = "버섯",
              ProductIcon = "icon_nat_mushroom",
              ProductTags = new[] { new Tag { Id = "eatable", Level = 1 }, new Tag { Id = "mushroom", Level = 1 } },
              SeedProductId = "mushroom_seed_crop",
              SeedProductName = "버섯 포자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 21600.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 4,
              RequiredFertilizer = 80,
              AdditionalProduct = 8,
              Survivability = 0.80f,
              Preference = Shared.Region.Biome.TemperateForest,
              GrownLooks = new[] { "MR01" },
              GrowingLook = "sprout_01",
              DeadLook = "AG03_01"
          } },
        { "oleander_seed", new CropInfo
          {
              SeedId = "oleander_seed",
              Name = "협죽도",
              Icon = "icon_nat_oleander",
              MaxLevel = 60,
              ProductId = "oleander_crop",
              ProductName = null,
              ProductIcon = null,
              ProductTags = null,
              SeedProductId = "oleander_seed_crop",
              SeedProductName = "협죽도 종자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 86400.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 40,
              RequiredFertilizer = 120,
              AdditionalProduct = 12,
              Survivability = 0.80f,
              Preference = Shared.Region.Biome.Grassland,
              GrownLooks = new[] { "BS09" },
              GrowingLook = "ML11_02",
              DeadLook = "AG03_01"
          } },
        { "onion_seed", new CropInfo
          {
              SeedId = "onion_seed",
              Name = "양파",
              Icon = "icon_nat_farm_onion",
              MaxLevel = 60,
              ProductId = "onion_crop",
              ProductName = "양파 구근",
              ProductIcon = "icon_nat_farm_onion",
              ProductTags = new[] { new Tag { Id = "eatable", Level = 1 }, new Tag { Id = "vegetable", Level = 1 } },
              SeedProductId = "onion_seed_crop",
              SeedProductName = "양파 종자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 930.0f,
              GrowPerLevel = 30.0f,
              RequiredWater = 2,
              RequiredFertilizer = 20,
              AdditionalProduct = 6,
              Survivability = 0.85f,
              Preference = Shared.Region.Biome.Grassland,
              GrownLooks = new[] { "HG01_01" },
              GrowingLook = "sprout_01",
              DeadLook = "AG03_01"
          } },
        { "orange_seed", new CropInfo
          {
              SeedId = "orange_seed",
              Name = "오렌지",
              Icon = "icon_nat_fruit_orange",
              MaxLevel = 60,
              ProductId = "orange_crop",
              ProductName = "오렌지",
              ProductIcon = "icon_nat_fruit_orange",
              ProductTags = new[] { new Tag { Id = "eatable", Level = 1 } },
              SeedProductId = "orange_seed_crop",
              SeedProductName = "오렌지 종자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 36000.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 10,
              RequiredFertilizer = 150,
              AdditionalProduct = 20,
              Survivability = 0.70f,
              Preference = Shared.Region.Biome.TropicalForest,
              GrownLooks = new[] { "FR05" },
              GrowingLook = "ML11_02",
              DeadLook = "AG03_01"
          } },
        { "oxalis_seed_blue", new CropInfo
          {
              SeedId = "oxalis_seed_blue",
              Name = "파란 사랑초",
              Icon = "icon_nat_oleander",
              MaxLevel = 60,
              ProductId = "oxalis_blue_crop",
              ProductName = "사랑초",
              ProductIcon = "icon_nat_oleander",
              ProductTags = new[] { new Tag { Id = "eatable", Level = 1 }, new Tag { Id = "oxalis_blue", Level = 1 }, new Tag { Id = "vegetable", Level = 1 } },
              SeedProductId = "oxalis_seed_blue_crop",
              SeedProductName = "사랑초 종자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 10800.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 8,
              RequiredFertilizer = 50,
              AdditionalProduct = 5,
              Survivability = 0.75f,
              Preference = Shared.Region.Biome.TropicalForest,
              GrownLooks = new[] { "VFF_02" },
              GrowingLook = "sprout_01",
              DeadLook = "AG03_01"
          } },
        { "oxalis_seed_red", new CropInfo
          {
              SeedId = "oxalis_seed_red",
              Name = "빨간 사랑초",
              Icon = "icon_nat_oleander",
              MaxLevel = 60,
              ProductId = "oxalis_red_crop",
              ProductName = "사랑초",
              ProductIcon = "icon_nat_oleander",
              ProductTags = new[] { new Tag { Id = "eatable", Level = 1 }, new Tag { Id = "oxalis_red", Level = 1 }, new Tag { Id = "vegetable", Level = 1 } },
              SeedProductId = "oxalis_seed_red_crop",
              SeedProductName = "사랑초 종자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 10800.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 8,
              RequiredFertilizer = 50,
              AdditionalProduct = 5,
              Survivability = 0.75f,
              Preference = Shared.Region.Biome.TropicalForest,
              GrownLooks = new[] { "VFF_03" },
              GrowingLook = "sprout_01",
              DeadLook = "AG03_01"
          } },
        { "oxalis_seed_yellow", new CropInfo
          {
              SeedId = "oxalis_seed_yellow",
              Name = "노란 사랑초",
              Icon = "icon_nat_oleander",
              MaxLevel = 60,
              ProductId = "oxalis_yellow_crop",
              ProductName = "사랑초",
              ProductIcon = "icon_nat_oleander",
              ProductTags = new[] { new Tag { Id = "eatable", Level = 1 }, new Tag { Id = "oxalis_yellow", Level = 1 }, new Tag { Id = "vegetable", Level = 1 } },
              SeedProductId = "oxalis_seed_yellow_crop",
              SeedProductName = "사랑초 종자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 10800.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 8,
              RequiredFertilizer = 50,
              AdditionalProduct = 5,
              Survivability = 0.75f,
              Preference = Shared.Region.Biome.TropicalForest,
              GrownLooks = new[] { "VFF_01" },
              GrowingLook = "sprout_01",
              DeadLook = "AG03_01"
          } },
        { "pepper_seed", new CropInfo
          {
              SeedId = "pepper_seed",
              Name = "피망",
              Icon = "icon_nat_farm_bellpepper",
              MaxLevel = 60,
              ProductId = "pepper_crop",
              ProductName = null,
              ProductIcon = null,
              ProductTags = null,
              SeedProductId = "pepper_seed_crop",
              SeedProductName = "피망 종자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 32400.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 10,
              RequiredFertilizer = 170,
              AdditionalProduct = 17,
              Survivability = 0.82f,
              Preference = Shared.Region.Biome.TropicalForest,
              GrownLooks = new[] { "VG07_07" },
              GrowingLook = "sprout_01",
              DeadLook = "AG03_01"
          } },
        { "persimmontree_seed", new CropInfo
          {
              SeedId = "persimmontree_seed",
              Name = "감나무",
              Icon = "icon_nat_persimmon",
              MaxLevel = 60,
              ProductId = "persimmontree_crop",
              ProductName = null,
              ProductIcon = null,
              ProductTags = new[] { new Tag { Id = "eatable", Level = 1 }, new Tag { Id = "grain", Level = 1 } },
              SeedProductId = "persimmontree_seed_crop",
              SeedProductName = "감나무 종자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 75600.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 10,
              RequiredFertilizer = 150,
              AdditionalProduct = 10,
              Survivability = 0.80f,
              Preference = Shared.Region.Biome.TemperateForest,
              GrownLooks = new[] { "pe_02_a" },
              GrowingLook = "ML11_02",
              DeadLook = "AG03_01"
          } },
        { "poppy_seed", new CropInfo
          {
              SeedId = "poppy_seed",
              Name = "개양귀비",
              Icon = "icon_nat_farm_poppy",
              MaxLevel = 60,
              ProductId = "poppy_crop",
              ProductName = null,
              ProductIcon = null,
              ProductTags = null,
              SeedProductId = "poppy_seed_crop",
              SeedProductName = "양귀비 종자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 43200.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 16,
              RequiredFertilizer = 150,
              AdditionalProduct = 14,
              Survivability = 0.85f,
              Preference = Shared.Region.Biome.Grassland,
              GrownLooks = new[] { "GC12" },
              GrowingLook = "sprout_01",
              DeadLook = "AG03_01"
          } },
        { "potato_seed", new CropInfo
          {
              SeedId = "potato_seed",
              Name = "감자",
              Icon = "icon_nat_farm_potato",
              MaxLevel = 60,
              ProductId = "potato_crop",
              ProductName = "감자",
              ProductIcon = "icon_nat_farm_potato",
              ProductTags = new[] { new Tag { Id = "eatable", Level = 1 }, new Tag { Id = "vegetable", Level = 1 } },
              SeedProductId = "potato_seed_crop",
              SeedProductName = "감자 종자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 1830.0f,
              GrowPerLevel = 30.0f,
              RequiredWater = 2,
              RequiredFertilizer = 30,
              AdditionalProduct = 6,
              Survivability = 0.85f,
              Preference = Shared.Region.Biome.TemperateForest,
              GrownLooks = new[] { "AG07" },
              GrowingLook = "sprout_01",
              DeadLook = "AG03_01"
          } },
        { "pumpkin_seed", new CropInfo
          {
              SeedId = "pumpkin_seed",
              Name = "호박",
              Icon = "icon_nat_farm_pumpkin",
              MaxLevel = 60,
              ProductId = "pumpkin_crop",
              ProductName = "호박",
              ProductIcon = "icon_nat_farm_pumpkin",
              ProductTags = new[] { new Tag { Id = "eatable", Level = 1 }, new Tag { Id = "vegetable", Level = 1 } },
              SeedProductId = "pumpkin_seed_crop",
              SeedProductName = "호박 종자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 1830.0f,
              GrowPerLevel = 30.0f,
              RequiredWater = 3,
              RequiredFertilizer = 30,
              AdditionalProduct = 6,
              Survivability = 0.85f,
              Preference = Shared.Region.Biome.TemperateForest,
              GrownLooks = new[] { "HG11" },
              GrowingLook = "sprout_01",
              DeadLook = "AG03_01"
          } },
        { "rice_seed", new CropInfo
          {
              SeedId = "rice_seed",
              Name = "벼",
              Icon = "icon_nat_farm_rice",
              MaxLevel = 60,
              ProductId = "rice_crop",
              ProductName = "쌀",
              ProductIcon = "icon_nat_farm_rice",
              ProductTags = new[] { new Tag { Id = "eatable", Level = 1 }, new Tag { Id = "grain", Level = 1 } },
              SeedProductId = "rice_seed_crop",
              SeedProductName = "쌀 종자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 10800.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 4,
              RequiredFertilizer = 70,
              AdditionalProduct = 7,
              Survivability = 0.83f,
              Preference = Shared.Region.Biome.TemperateForest,
              GrownLooks = new[] { "AG14_01" },
              GrowingLook = "sprout_01",
              DeadLook = "AG03_01"
          } },
        { "rose_damask_seed", new CropInfo
          {
              SeedId = "rose_damask_seed",
              Name = "다마스크 장미",
              Icon = "icon_nat_rose",
              MaxLevel = 60,
              ProductId = "rose_damask_crop",
              ProductName = "다마스크 장미",
              ProductIcon = "icon_nat_rose",
              ProductTags = new[] { new Tag { Id = "flower", Level = 1 } },
              SeedProductId = "rose_damask_seed_crop",
              SeedProductName = "다마스크 장미 종자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 21600.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 10,
              RequiredFertilizer = 70,
              AdditionalProduct = 7,
              Survivability = 0.80f,
              Preference = Shared.Region.Biome.Grassland,
              GrownLooks = new[] { "SH14_01" },
              GrowingLook = "sprout_01",
              DeadLook = "AG03_01"
          } },
        { "rose_misterlincoln_seed", new CropInfo
          {
              SeedId = "rose_misterlincoln_seed",
              Name = "미스터 링컨",
              Icon = "icon_nat_rose",
              MaxLevel = 60,
              ProductId = "rose_misterlincoln_crop",
              ProductName = "미스터 링컨",
              ProductIcon = "icon_nat_rose",
              ProductTags = new[] { new Tag { Id = "flower", Level = 1 } },
              SeedProductId = "rose_misterlincoln_seed_crop",
              SeedProductName = "미스터 링컨 종자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 10800.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 5,
              RequiredFertilizer = 50,
              AdditionalProduct = 5,
              Survivability = 0.80f,
              Preference = Shared.Region.Biome.Grassland,
              GrownLooks = new[] { "SH14_02" },
              GrowingLook = "sprout_01",
              DeadLook = "AG03_01"
          } },
        { "sugarcane_seed", new CropInfo
          {
              SeedId = "sugarcane_seed",
              Name = "사탕수수",
              Icon = "icon_nat_sugarcane",
              MaxLevel = 60,
              ProductId = "sugarcane_crop",
              ProductName = "사탕수수",
              ProductIcon = "icon_nat_sugarcane",
              ProductTags = null,
              SeedProductId = "sugarcane_seed_crop",
              SeedProductName = "사탕수수 종자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 21600.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 8,
              RequiredFertilizer = 80,
              AdditionalProduct = 10,
              Survivability = 0.83f,
              Preference = Shared.Region.Biome.TropicalForest,
              GrownLooks = new[] { "TR18" },
              GrowingLook = "sprout_01",
              DeadLook = "AG03_01"
          } },
        { "sunflower_seed", new CropInfo
          {
              SeedId = "sunflower_seed",
              Name = "해바라기",
              Icon = "icon_nat_sunflower",
              MaxLevel = 60,
              ProductId = "sunflower_crop",
              ProductName = "해바라기",
              ProductIcon = "icon_nat_sunflower",
              ProductTags = new[] { new Tag { Id = "flower", Level = 1 } },
              SeedProductId = "sunflower_seed_crop",
              SeedProductName = "해바라기 종자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 10800.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 5,
              RequiredFertilizer = 50,
              AdditionalProduct = 5,
              Survivability = 0.80f,
              Preference = Shared.Region.Biome.Grassland,
              GrownLooks = new[] { "FL09" },
              GrowingLook = "sprout_01",
              DeadLook = "AG03_01"
          } },
        { "taro_seed", new CropInfo
          {
              SeedId = "taro_seed",
              Name = "타로",
              Icon = "icon_nat_taro",
              MaxLevel = 60,
              ProductId = "taro_crop",
              ProductName = "타로",
              ProductIcon = "icon_nat_taro",
              ProductTags = new[] { new Tag { Id = "eatable", Level = 1 }, new Tag { Id = "vegetable", Level = 1 } },
              SeedProductId = "taro_seed_crop",
              SeedProductName = "타로 종자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 32400.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 10,
              RequiredFertilizer = 170,
              AdditionalProduct = 6,
              Survivability = 0.80f,
              Preference = Shared.Region.Biome.TropicalForest,
              GrownLooks = new[] { "FL59" },
              GrowingLook = "sprout_01",
              DeadLook = "AG03_01"
          } },
        { "teatree_seed", new CropInfo
          {
              SeedId = "teatree_seed",
              Name = "차나무",
              Icon = "icon_nat_leaf_tea",
              MaxLevel = 60,
              ProductId = "teatree_crop",
              ProductName = null,
              ProductIcon = null,
              ProductTags = null,
              SeedProductId = "teatree_seed_crop",
              SeedProductName = "차나무 종자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 32400.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 10,
              RequiredFertilizer = 150,
              AdditionalProduct = 13,
              Survivability = 0.83f,
              Preference = Shared.Region.Biome.Tundra,
              GrownLooks = new[] { "AGR02" },
              GrowingLook = "ML11_02",
              DeadLook = "AG03_01"
          } },
        { "tomato_seed", new CropInfo
          {
              SeedId = "tomato_seed",
              Name = "토마토",
              Icon = "icon_nat_farm_tomato",
              MaxLevel = 60,
              ProductId = "tomato_crop",
              ProductName = "토마토",
              ProductIcon = "icon_nat_farm_tomato",
              ProductTags = new[] { new Tag { Id = "eatable", Level = 1 }, new Tag { Id = "vegetable", Level = 1 } },
              SeedProductId = "tomato_seed_crop",
              SeedProductName = "토마토 종자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 16200.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 5,
              RequiredFertilizer = 80,
              AdditionalProduct = 10,
              Survivability = 0.80f,
              Preference = Shared.Region.Biome.TemperateForest,
              GrownLooks = new[] { "AG15" },
              GrowingLook = "sprout_01",
              DeadLook = "AG03_01"
          } },
        { "valentine_cacaotree_seed", new CropInfo
          {
              SeedId = "valentine_cacaotree_seed",
              Name = "카카오 나무",
              Icon = "icon_nat_farm_cacaobean",
              MaxLevel = 60,
              ProductId = "valentine_cacaotree_crop",
              ProductName = null,
              ProductIcon = null,
              ProductTags = new[] { new Tag { Id = "eatable", Level = 1 } },
              SeedProductId = "valentine_cacaotree_seed_crop",
              SeedProductName = "카카오 나무 종자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 43200.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 15,
              RequiredFertilizer = 150,
              AdditionalProduct = 5,
              Survivability = 0.55f,
              Preference = Shared.Region.Biome.Invalid,
              GrownLooks = new[] { "ca01" },
              GrowingLook = "ML11_02",
              DeadLook = "AG03_01"
          } },
        { "violettulip_seed", new CropInfo
          {
              SeedId = "violettulip_seed",
              Name = "보라튤립",
              Icon = "icon_nat_flower_violoettulip",
              MaxLevel = 60,
              ProductId = "violettulip_crop",
              ProductName = null,
              ProductIcon = null,
              ProductTags = null,
              SeedProductId = "violettulip_seed_crop",
              SeedProductName = "보라튤립 종자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 32400.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 12,
              RequiredFertilizer = 150,
              AdditionalProduct = 12,
              Survivability = 0.83f,
              Preference = Shared.Region.Biome.Desert,
              GrownLooks = new[] { "FL43" },
              GrowingLook = "sprout_01",
              DeadLook = "AG03_01"
          } },
        { "watermelon_01_seed", new CropInfo
          {
              SeedId = "watermelon_01_seed",
              Name = "수박",
              Icon = "icon_nat_farm_watermelon_01",
              MaxLevel = 60,
              ProductId = "watermelon_01_crop",
              ProductName = "수박",
              ProductIcon = "icon_nat_farm_watermelon_01",
              ProductTags = new[] { new Tag { Id = "eatable", Level = 1 }, new Tag { Id = "fruit", Level = 1 } },
              SeedProductId = "watermelon_01_seed_crop",
              SeedProductName = "수박 종자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 14400.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 5,
              RequiredFertilizer = 50,
              AdditionalProduct = 10,
              Survivability = 0.80f,
              Preference = Shared.Region.Biome.TemperateForest,
              GrownLooks = new[] { "HG08" },
              GrowingLook = "sprout_01",
              DeadLook = "AG03_01"
          } },
        { "wheat_seed", new CropInfo
          {
              SeedId = "wheat_seed",
              Name = "밀",
              Icon = "icon_nat_farm_wheat",
              MaxLevel = 60,
              ProductId = "wheat_crop",
              ProductName = "밀",
              ProductIcon = "icon_nat_farm_wheat",
              ProductTags = new[] { new Tag { Id = "eatable", Level = 1 }, new Tag { Id = "grain", Level = 1 } },
              SeedProductId = "wheat_seed_crop",
              SeedProductName = "밀 종자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 5400.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 3,
              RequiredFertilizer = 50,
              AdditionalProduct = 6,
              Survivability = 0.80f,
              Preference = Shared.Region.Biome.TemperateForest,
              GrownLooks = new[] { "AG09" },
              GrowingLook = "sprout_01",
              DeadLook = "AG03_01"
          } },
        { "white_rose_seed", new CropInfo
          {
              SeedId = "white_rose_seed",
              Name = "하얀 장미",
              Icon = "icon_nat_rose",
              MaxLevel = 60,
              ProductId = "white_rose_crop",
              ProductName = null,
              ProductIcon = null,
              ProductTags = new[] { new Tag { Id = "eatable", Level = 1 } },
              SeedProductId = "white_rose_seed_crop",
              SeedProductName = "하얀 장미 종자",
              SeedProductIcon = "icon_nat_farm_seed",
              GrowBase = 9000.0f,
              GrowPerLevel = 0.0f,
              RequiredWater = 5,
              RequiredFertilizer = 50,
              AdditionalProduct = 10,
              Survivability = 0.80f,
              Preference = Shared.Region.Biome.TemperateForest,
              GrownLooks = new[] { "GD45" },
              GrowingLook = "sprout_01",
              DeadLook = "AG03_01"
          } },
    };

    public static bool TryGet(string seedPrototype, out CropInfo info)
    {
        return ById.TryGetValue(seedPrototype ?? string.Empty, out info);
    }

    /// <summary>เมล็ดชนิดนี้ปลูกได้ไหม</summary>
    public static bool IsSeed(string seedPrototype)
    {
        return !string.IsNullOrEmpty(seedPrototype) && ById.ContainsKey(seedPrototype);
    }

    // ---------------------------------------------------------------- ปุ๋ย
    /// <summary>ไอเทมชิ้นนี้ให้ปุ๋ยกี่หน่วย — (ค่าที่เลเวล 1, เพิ่มต่อ 1 เลเวล)</summary>
    public static readonly Dictionary<string, (float Base, float PerLevel)> FertilizerPower =
        new Dictionary<string, (float, float)>
    {
        { "clay", (5.00f, 0.0000f) },
        { "clay_gray", (25.00f, 0.0000f) },
        { "crab_shell", (25.00f, 0.0000f) },
        { "dump", (10.00f, 0.0000f) },
        { "fertilizer_01", (6.60f, 0.6000f) },
        { "fertilizer_01_dump", (20.00f, 0.0000f) },
        { "fertilizer_01_fruit", (15.00f, 0.0000f) },
        { "fertilizer_02", (11.00f, 1.0000f) },
        { "fertilizer_02_dump", (35.00f, 0.0000f) },
        { "fertilizer_02_fruit", (25.00f, 0.0000f) },
        { "fertilizer_02_grain", (25.00f, 0.0000f) },
        { "fertilizer_02_meat", (45.00f, 0.0000f) },
        { "fertilizer_liquid_01", (11.00f, 1.0000f) },
        { "fertilizer_normal", (1.50f, 1.5000f) },
        { "moss", (25.00f, 0.0000f) },
    };

    /// <summary>ปุ๋ยที่ได้จากไอเทมชิ้นนี้ที่เลเวลนี้ (0 = ไม่ใช่ปุ๋ย)</summary>
    public static float FertilizerOf(string prototype, int level)
    {
        if (string.IsNullOrEmpty(prototype) || !FertilizerPower.TryGetValue(prototype, out var v))
        {
            return 0f;
        }
        float amount = v.Base + v.PerLevel * (level - 1);
        return amount < 0f ? 0f : amount;
    }

    // ---------------------------------------------------------------- ภาชนะตักน้ำ
    /// <summary>ภาชนะใบนี้ตักน้ำได้กี่หน่วย — (ค่าที่เลเวล 1, เพิ่มต่อ 1 เลเวล)</summary>
    public static readonly Dictionary<string, (float Base, float PerLevel)> ContainerCapacity =
        new Dictionary<string, (float, float)>
    {
        { "bag_metal_bucket", (4.03f, 0.0250f) },
        { "bag_water_bamboo", (1.02f, 0.0250f) },
        { "bag_water_coconut", (1.02f, 0.0250f) },
        { "bag_water_fabric", (6.03f, 0.0250f) },
        { "bag_water_horn", (3.02f, 0.0250f) },
        { "bag_water_pouch", (1.02f, 0.0250f) },
        { "bag_water_sack", (9.03f, 0.0250f) },
        { "bag_water_sack_event", (9.00f, 0.0000f) },
        { "bone_head", (1.05f, 0.0500f) },
        { "bone_head_big", (2.55f, 0.0500f) },
        { "bone_head_carni", (1.02f, 0.0250f) },
        { "bone_head_herv", (2.05f, 0.0500f) },
        { "bottle_wine", (2.00f, 0.0000f) },
        { "cheat_bag_water", (1000.00f, 0.0000f) },
        { "chrismas_onehand_beer_mug", (1.00f, 0.0000f) },
        { "chrismas_onehand_beer_mug_2018", (2.00f, 0.0000f) },
        { "clam_shell", (2.00f, 0.0000f) },
        { "crab_shell", (1.00f, 0.0000f) },
        { "fish_can", (1.00f, 0.0000f) },
        { "fish_vynil", (1.00f, 0.0000f) },
        { "hat_bike", (3.00f, 0.0000f) },
        { "hat_bike_store", (3.00f, 0.0000f) },
        { "hat_bucket", (3.00f, 0.0000f) },
        { "hat_bucket_starting", (3.00f, 0.0000f) },
        { "hat_bucket_store", (3.00f, 0.0000f) },
        { "hat_statue_01_store", (3.00f, 0.0000f) },
        { "jar", (10.00f, 0.0000f) },
        { "petbottle", (1.00f, 0.0000f) },
        { "pot_01", (1.05f, 0.0500f) },
        { "pot_02", (2.05f, 0.0500f) },
        { "pot_03", (3.05f, 0.0500f) },
        { "s02_container_petbottle", (1.00f, 0.0000f) },
        { "xmas_bone_head", (3.00f, 0.0000f) },
        { "xmas_bone_head_big", (5.00f, 0.0000f) },
    };

    /// <summary>ภาชนะใบนี้ตักน้ำได้กี่หน่วยที่เลเวลนี้ (0 = ไม่ใช่ภาชนะ)</summary>
    public static float CapacityOf(string prototype, int level)
    {
        if (string.IsNullOrEmpty(prototype) || !ContainerCapacity.TryGetValue(prototype, out var v))
        {
            return 0f;
        }
        float amount = v.Base + v.PerLevel * (level - 1);
        return amount < 0f ? 0f : amount;
    }
}
